### ISSUE TITLE
ORM.Count统计直接传gtime.time会导致统计结果不一致

### ISSUE THREAD

**Issue by guikeyy** [gogf/gf#2181]
```go
startTime := gtime.New(1664640000)
endTime := gtime.New(1665308819)
// 如果gtime.time不格式化一下startTime.String()执行语句，会导致count结果不准确
db.Ctx(ctx).Model("xxxx bcnbs").Where("bcnbs.LastEditDate >= ? and bcnbs.LastEditDate <= ?", startTime, endTime).Count()
```

**Comment by CCpro10** [comment]
这里就是要用 startTime.String() ，应该是你的使用方法错了

**Comment by zhonghuaxunGM** [comment]
@guikeyy 
Please provide the corresponding gf version and the corresponding minimum runnable code example.

And I can't reproduce this problem on master latest code 
`github.com/gogf/gf/v2 v2.2.1-0.20221014021027-2598745e50c9`

You can view the code sample here.
https://github.com/zhonghuaxunGM/go-gf-issue/tree/issue-2181

If you still have questions, you can reply here. This issue is closed now.

**Comment by zhonghuaxunGM** [comment]
sorry, my fault. I will try to fix it. 
I suspect it's timezone related.

**Comment by zhonghuaxunGM** [comment]
@guikeyy 

Please increase the parameter loc when setting the database link ,
like `link: "user:pwd@tcp(127.0.0.1:3306)/test?loc=Local" `

You can view the code sample here.
https://github.com/zhonghuaxunGM/go-gf-issue/tree/issue-2181

doc:
https://goframe.org/pages/viewpage.action?pageId=3672072

**Comment by guikeyy** [comment]
> @guikeyy
> 
> Please increase the parameter `loc` when setting the database link , like `link: "user:pwd@tcp(127.0.0.1:3306)/test?loc=Local" `
> 
> You can view the code sample here. https://github.com/zhonghuaxunGM/go-gf-issue/tree/issue-2181
> 
> doc: https://goframe.org/pages/viewpage.action?pageId=3672072

 https://goframe.org/pages/viewpage.action?pageId=3672072
明白了，谢谢～
