### ISSUE TITLE
Default glog.HandlerStructure and HandlerJson use config file logger ctxKeys'  key name to stdout

### ISSUE THREAD

**Issue by ragnaros2046** [gogf/gf#3395]
**Package that You wish to enhance**
Now, If I set config file as follow:

> logger: 
   ctxKeys: ["userid"]

and use

> g.Log().SetHandlers(glog.HandlerStructure)

log would be 

> Time="2024-03-18 20:31:50.126" TraceId=7cbcf9ff1703be17b9e8ca63ce799a3a CtxStr=127.0.0.1:14884 Level=WARN

It user "CtxStr" instead of the key name "userid" in config file.

Because glog HandlerInput struct set CtxStr as string. Could we make it as a map[string]string?

expected stdout:

> Time="2024-03-18 20:31:50.126" TraceId=7cbcf9ff1703be17b9e8ca63ce799a3a **userid**=127.0.0.1:14884 Level=WARN

**Comment by Blacknight1260** [comment]
What the heck is this???

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: ragnaros2046 ***@***.***>
Sent: Monday, March 18, 2024 8:43:25 PM
To: gogf/gf ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gogf/gf] Default glog.HandlerStructure and HandlerJson use config file logger ctxKeys' key name to stdout (Issue #3395)


Package that You wish to enhance
Now, If I set config file as follow:

logger:
ctxKeys: ["userid"]

and use

g.Log().SetHandlers(glog.HandlerStructure)

log would be

Time="2024-03-18 20:31:50.126" TraceId=7cbcf9ff1703be17b9e8ca63ce799a3a CtxStr=127.0.0.1:14884 Level=WARN

It user "CtxStr" instead of the key name "userid" in config file.

Because glog HandlerInput struct set CtxStr as string. Could we make it as a map[string]string?

expected stdout:

Time="2024-03-18 20:31:50.126" TraceId=7cbcf9ff1703be17b9e8ca63ce799a3a userid=127.0.0.1:14884 Level=WARN
