### ISSUE TITLE
AutoMigrate

### ISSUE THREAD

**Issue by HHC26** [gogf/gf#3766]
### Description

The AutoMigration feature is quite practical,
Please consider adding it

**Comment by niluan304** [comment]
> Sorry but I do not think it a good feature and will not be considered
>> [gqcn](https://github.com/gqcn) commented [on Oct 14, 2020](https://github.com/gogf/gf/issues/943#issuecomment-708390027)


related issue #943 #475 #779

**Comment by UncleChair** [comment]
Migration like Laravel may not be a good idea since it may make database schema unmaintainable (especially some old project with lots of s**t). But indeed migration is helpful in some cases for developers, so I think it is quite a dilemma  for GoFrame to choose whether to add this function since both case has its own reasons. Besides, there already exists many migration tools write in go like [goose](https://github.com/pressly/goose) or [atlas](https://github.com/ariga/atlas). Goose is more like Laravel one and Atlas is more powerful but may charge for some advanced features, you may also find you own migration tools for your requirement.
