### ISSUE TITLE
cmd/gf: When initing the project, it is expected that the parameters can be passed directly to the github project address.

### ISSUE THREAD

**Issue by wangle201210** [gogf/gf#3941]
### Description

期望 gf init github.com/wanna/demo 能等效gf init -g github.com/wanna/demo demo

**Comment by gqcn** [comment]
@wangle201210 When designing the `gf init` command, we referred more to the `git init` command rather than the `go mod init` command. As a result, the `gf init` command allows specifying the directory path of the project as a parameter, whereas `go mod init` does not. If we were to support the `git init MODULE_NAME` style, it would conflict with the current command design and lead to version incompatibility issues.
